import { cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const modules = join(root, 'node_modules');
const target = join(root, 'static', 'vendor');

await rm(target, { recursive: true, force: true });
await mkdir(target, { recursive: true });

async function copy(source, destination) {
  await mkdir(dirname(destination), { recursive: true });
  await cp(source, destination, { recursive: true });
}

await copy(join(modules, 'three', 'build', 'three.module.js'), join(target, 'three', 'build', 'three.module.js'));
await copy(join(modules, 'three', 'build', 'three.core.js'), join(target, 'three', 'build', 'three.core.js'));
const threeAddons = [
  'libs/meshopt_decoder.module.js',
  'loaders/GLTFLoader.js',
  'postprocessing/EffectComposer.js',
  'postprocessing/MaskPass.js',
  'postprocessing/Pass.js',
  'postprocessing/RenderPass.js',
  'postprocessing/ShaderPass.js',
  'postprocessing/UnrealBloomPass.js',
  'shaders/CopyShader.js',
  'shaders/LuminosityHighPassShader.js',
  'utils/BufferGeometryUtils.js',
  'utils/SkeletonUtils.js',
];
for (const addon of threeAddons) {
  await copy(join(modules, 'three', 'examples', 'jsm', addon), join(target, 'three', 'examples', 'jsm', addon));
}
await copy(join(modules, 'html2canvas', 'dist', 'html2canvas.min.js'), join(target, 'html2canvas', 'html2canvas.min.js'));
await copy(join(modules, 'qrcodejs', 'qrcode.min.js'), join(target, 'qrcodejs', 'qrcode.min.js'));

const fontPackages = [
  ['inter', ['latin-ext-300.css', 'latin-ext-400.css', 'latin-ext-500.css', 'latin-ext-600.css']],
  ['cinzel', ['latin-ext-400.css', 'latin-ext-600.css']],
  ['cinzel-decorative', ['latin-ext-700.css', 'latin-ext-900.css']],
  ['cormorant-garamond', ['latin-ext-300.css', 'latin-ext-300-italic.css', 'latin-ext-600.css', 'latin-ext-600-italic.css']],
  ['ibm-plex-mono', ['latin-ext-300.css', 'latin-ext-400.css']],
  ['dm-sans', ['latin-ext-300.css', 'latin-ext-400.css', 'latin-ext-500.css']],
];

let bundle = '/* Pinned, self-hosted font faces generated by scripts/sync-vendor.mjs. */\n';
for (const [family, sheets] of fontPackages) {
  const packageRoot = join(modules, '@fontsource', family);
  const familyTarget = join(target, 'fonts', family);
  for (const sheet of sheets) {
    const css = await readFile(join(packageRoot, sheet), 'utf8');
    for (const match of css.matchAll(/url\(\.\/files\/([^)]+)\)/g)) {
      await copy(join(packageRoot, 'files', match[1]), join(familyTarget, 'files', match[1]));
    }
    bundle += `\n/* @fontsource/${family}/${sheet} */\n`;
    bundle += css.replaceAll('./files/', `./${family}/files/`);
  }
}
await writeFile(join(target, 'fonts', 'fonts.css'), bundle);

const manifest = {
  generatedBy: relative(root, fileURLToPath(import.meta.url)),
  dependencies: {
    three: '0.185.1', html2canvas: '1.4.1', qrcodejs: '1.0.0',
    fontsource: '5.3.0',
  },
};
await writeFile(join(target, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`);
console.log(`Self-hosted browser dependencies written to ${relative(root, target)}`);
